retest

diff --git a/.github/workflows/docker-build-push-image.yml b/.github/workflows/docker-build-push-image.yml
--- a/.github/workflows/docker-build-push-image.yml
+++ b/.github/workflows/docker-build-push-image.yml
@@ -65,65 +65,56 @@ jobs:
     - name: check images after pull
       run: docker images
 
-  deploy:
-        needs: build
-        runs-on: self-hosted
-        steps:
-          - name: Check Docker Installation
-            run: |
-              if ! [ -x "$(command -v docker)" ]; then
-                echo "Error: Docker is not installed." >&2
-                exit 1
-              fi
-          - name: Pull image from docker hub
-            run: sudo docker pull maxtheservice/demo:latest
-          - name: Delete existing container
-            run: |
-              if [ "$(sudo docker ps -aq -f name=demo)" ]; then
-                sudo docker rm -f demo
-              fi
-          - name: Run demo container
-            run: sudo docker run -p 8080:8080 --name demo --network demo maxtheservice/demo:latest
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
   # deploy:
-  #     needs: build
-  #     runs-on: self-hosted
-  #     steps:
-  #       - name: Check Docker Installation
-  #         run: |
-  #           if ! [ -x "$(command -v docker)" ]; then
-  #             echo "Error: Docker is not installed." >&2
-  #             exit 1
-  #           fi
-  #       - name: Pull image from docker hub
-  #         run: sudo docker pull maxtheservice/demo:latest
-  #       - name: Delete existing container
-  #         run: |
-  #           if [ "$(sudo docker ps -aq -f name=demo)" ]; then
-  #             sudo docker rm -f demo
-  #           fi
-  #       # - name: Remove all containers
-  #       # docker container prune -f
-  #       # - name: Run mysql container
-  #         # run: sudo docker run --name mysqldb 
-  #         # -e MYSQL_ROOT_USER=root -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABSE=demodb 
-  #         # -p 3306:3306 --network demo mysql:8.0
-  #       - name: Run demo container
-  #         run: sudo docker run -p 8080:8080 --name demo --network demo maxtheservice/demo:latest
+  #       needs: build
+  #       runs-on: self-hosted
+  #       steps:
+  #         - name: Check Docker Installation
+  #           run: |
+  #             if ! [ -x "$(command -v docker)" ]; then
+  #               echo "Error: Docker is not installed." >&2
+  #               exit 1
+  #             fi
+  #         - name: Pull image from docker hub
+  #           run: sudo docker pull maxtheservice/demo:latest
+  #         - name: Delete existing container
+  #           run: |
+  #             if [ "$(sudo docker ps -aq -f name=demo)" ]; then
+  #               sudo docker rm -f demo
+  #             fi
+  #         - name: Run demo container
+  #           run: sudo docker run -p 8080:8080 --name demo --network demo maxtheservice/demo:latest
+
+
+
+
+
+
+
+  deploy:
+      needs: build
+      runs-on: self-hosted
+      steps:
+        - name: Check Docker Installation
+          run: |
+            if ! [ -x "$(command -v docker)" ]; then
+              echo "Error: Docker is not installed." >&2
+              exit 1
+            fi
+        - name: Pull image from docker hub
+          run: sudo docker pull maxtheservice/demo:latest
+        - name: Delete existing container
+          run: |
+            if [ "$(sudo docker ps -aq -f name=demo)" ]; then
+              sudo docker rm -f demo
+            fi
+        - name: Remove all containers
+          run: |
+              sudo docker container prune -f
+        - name: Run mysql container
+          run: sudo docker run --name mysqldb -e MYSQL_ROOT_USER=root -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABSE=demodb -p 3306:3306 --network demo mysql:8.0
+        - name: Run demo container
+          run: sudo docker run -p 8080:8080 --name demo --network demo maxtheservice/demo:latest
       
         
 
