ec2 instance workflow

diff --git a/.github/workflows/docker-build-push-image.yml b/.github/workflows/docker-build-push-image.yml
--- a/.github/workflows/docker-build-push-image.yml
+++ b/.github/workflows/docker-build-push-image.yml
@@ -17,8 +17,8 @@ jobs:
 
   build:
 
-    # runs-on: ubuntu-latest
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
+    
 
     steps:
     - uses: actions/checkout@v4
@@ -65,7 +65,25 @@ jobs:
     - name: check images after pull
       run: docker images
 
-
+  deploy:
+      needs: build
+      runs-on: self-hosted
+      steps:
+        - name: Check Docker Installation
+          run: |
+            if ! [ -x "$(command -v docker)" ]; then
+              echo "Error: Docker is not installed." >&2
+              exit 1
+            fi
+        - name: Pull image from docker hub
+          run: sudo docker pull maxtheservice/demo:latest
+        - name: Delete existing container
+          run: |
+            if [ "$(sudo docker ps -aq -f name=demo)" ]; then
+              sudo docker rm -f demo
+            fi
+        - name: Run docker container
+          run: sudo docker run -p 8080:8080 --name demo maxtheservice/demo:latest
       
 
       # - name: build the docker image method 1
